In [59]:
import numpy as np

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [81]:
np.zeros((3,5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [83]:
np.ones((3,4,5), dtype = "int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [97]:
np.full((2,3), 6, dtype = "float")

array([[6., 6., 6.],
       [6., 6., 6.]])

In [111]:
np.arange(2, 10, dtype = "float")

array([2., 3., 4., 5., 6., 7., 8., 9.])